name: build_test

on:
  push:
    branches: [ "main" ]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.14
      uses: actions/setup-python@v3
      with:
        python-version: "3.14"
    - name: Install dependencies
      run:  pip install -r requirements.txt
     
    - name: Test with pytest
      run:  py.py
